### PR TITLE
Added Categories Internships and Jobs

### PR DESCRIPTION
**Pull request by lalitmee**
I have given space for writing down the links in the categories.

### CODE REVIEW

**Comment by sdmg15** [comment]
Please can you elaborate more about that.
Thanks!

**Comment by lalitmee** [comment]
Actually, issue related to this PR was saying something like that **Add categories Internships and jobs**. So I have added Internships and jobs in the Index and I also have created space to add contents to them. If I interpreted the issue in right way.

**Comment by sdmg15** [comment]
Hi,
The person who opened the issue didn't respond for now, 
Maybe he'll not work on hit again, or you would do so?
Thanks.

**Comment by amirmedina** [comment]
Tq all

**Comment by lalitmee** [comment]
@sdmg15 I will work on this repo continuously. 

What you said in the previous comment, I didn't understand.

**Comment by sdmg15** [comment]
Hey, what I was saying is that, the one who opened the issue didn't respond since.
And what I was asking is if you will work in that category so that I can merge.
Thanks.

**Comment by lalitmee** [comment]
Yeah, I will. As I am saying that I will work but I will need help.

**Pull request merged**
