### PR TITLE
Remove sexist stuff

### PR DESCRIPTION
**Pull request by demimismo**
Much better now!

### CODE REVIEW

**Comment by emanh1** [comment]
O.o

**Comment by Vivalas** [comment]
Explain again how this is sexist..?

**Comment by emanh1** [comment]
https://www.youtube.com/user/CodeBabes/videos
Its videos has sexist thumbnail lol

**Comment by demimismo** [comment]
Sorry, I didn't explain in the PR because I thought it was straightforward. 

"Codebabes" and "itcuties" are websites stereotyping women on the basis of sex, that's the very definition of sexism. 

I like this compilation, but I think it would better without those particular two links.

**Comment by tommyip** [comment]
The content/quality in those videos are not that great anyway.

**Comment by Vivalas** [comment]
They're literally made by women though.

**Comment by tommyip** [comment]
I would also consider them as click bait videos; the signal to noise ratio is very low.

- The first 20 seconds of the video is literally showing the girl's body
- In the screencasts, half of the screen is occupied by the girls

You can find much more educational videos somewhere else.

**Comment by Vivalas** [comment]
I support it for reasons like that but not things like "lol sexism i am offend".

**Comment by demimismo** [comment]
@Vivalas yep it's sexist. You choose not to understand that, it's fine. That doesn't make the content less sexist, of course.

**Comment by MarkLiamP** [comment]
@demimismo Sorry but no,  that is not an example of sexism.  It's also not an example of stereotyping for that matter.  

Those are grown women capable of making their own decisions and they have clearly decided they're okay with using their looks to make money on those videos.  They are not children or helpless victims who need you to defend their honor.

**Comment by tommyip** [comment]
Yeah I agree that these are not examples of sexism, but tech channels that `use their looks to make money` are probably not the `Best websites a programmer should visit`.
[Thenewboston](https://www.youtube.com/user/thenewboston) and [Derek banas](https://www.youtube.com/user/derekbanas) offer similar and better tutorials with regard to the quality and content.

**Comment by demimismo** [comment]
> Those are grown women capable of making their own decisions and they have clearly decided they're okay with using their looks to make money on those videos. They are not children or helpless victims who need you to defend their honor.

I'm not defending anyone's honor. "Codebabes" and "it cuties" are using women to sell their content. Sexual objectification is sexism, wether the women are actively involved in the production of that content or not.

**Comment by Mohamed3on** [comment]
Oh wow, people are actually saying these videos are okay and not sexist? Have you seen the videos? I'm astonished that there even is a debate.

**Comment by Vivalas** [comment]
@demimismo

You can be as dogmatic as you want, but there is no discrimination against women or negative portrayal of women in these videos. That being said, they are indeed terrible sites to learn from and probably should be removed.

They could also just be on the list as a joke though, and I doubt anyone serious about learning programming would actually use these videos though, so whatever.

**Comment by demimismo** [comment]
@Vivalas anyone "serious about learning programming" should also learn a thing or two about sexism and just in general how to answer politely and behave in public. Good luck!

**Comment by Vivalas** [comment]
Golly gee we've moved on to personal denegration and passive aggression instead of dogmatism and still lack an argument. You're right though I'm done arguing about this, quite frankly it's silly.

**Comment by tommyip** [comment]
Can we just have this merged...

**Comment by Mohamed3on** [comment]
@tommyip Agreed. At least we all agree they're crap resources, so this should be straightforward.

**Comment by demimismo** [comment]
Closing, since #137 is much more complete and removes the same content.

**Pull request closed without merging**
