### PR TITLE
Removes the Revolution OS Linux Documentary link

### PR DESCRIPTION
**Pull request by Paradzayi**
This video is no longer on YouTube. So I think the link is no longer relevant.

### CODE REVIEW

**Comment by Paradzayi** [comment]
Thanks @sdmg15  for considering my PR, much appreciated.

**Comment by joelhandwell** [comment]
It's available here https://www.youtube.com/watch?v=jw8K460vx1c

**Comment by sdmg15** [comment]
@joelhandwell You can then PR it.

**Comment by joelhandwell** [comment]
@sdmg15 made PR. Thanks.

**Pull request merged**
