### PR TITLE
Feature/add awesome lint awesome bot

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**

### CODE REVIEW

**Comment by sdmg15** [comment]
Description for the PR needed.

**Comment by rachmadaniHaryono** [comment]
Add Travis configuration for these 2 bots

https://github.com/abdelhai/awesome-bots

https://github.com/sindresorhus/awesome-lint

When enabled on Travis a lint check will be performed by travis

**Comment by rachmadaniHaryono** [comment]
>How to fix automatically previous errors ? and also how to change Marker style should be ?

not it should be done manually, just as @awesome-bot said

**Comment by sdmg15** [comment]
But now for each commit , test are failing how to deal with?

**Pull request merged**
