### PR TITLE
Adds Angular 1 Style Guide

### PR DESCRIPTION
**Pull request by douglasg14b**
Adds Angular 1 style guide by John Papa (This is the officially endorsed style guide by the Angular team).

Thought this should be added considering how many developers use Angular, and more importantly how many tend to use it in a non-angular way.

### CODE REVIEW

**Comment by sdmg15** [comment]
Review the contribution guide and resolve conflicts.

**Comment by douglasg14b** [comment]
@sdmg15 I did initially, where does this not follow the style guide? 

Somehow conflicts appeared after the fact, I resolved the new conflicts, hopefully it stays that way.

**Comment by sdmg15** [comment]
Can't merge since now. Please review.

**Comment by douglasg14b** [comment]
@sdmg15 Resolved again..... 

image

**Comment by douglasg14b** [comment]
@sdmg15 Fixed space preventing link from being parsed

**Comment by douglasg14b** [comment]
@sdmg15 done

**Pull request merged**
