### PR TITLE
Listed everything alphabetically

### PR DESCRIPTION
**Pull request by iArunava**
@sdmg15 I think you should update the CONTRIBUTING.md to ask contributors to list their contributions alphabetically.

### CODE REVIEW

**Comment by sdmg15** [comment]
OMG, you did a large set !
isn't there a tool that can check that after each commit ?
THanks.

**Comment by iArunava** [comment]
Actually, I don't know anything in particular. But, I think I might be able to help. Give me some time, I'll get back to you. ok?

**Comment by sdmg15** [comment]
Sure.

**Comment by iArunava** [comment]
What I am thinking is to make a script that would verify if two files have the same content, irrespective of the line they are present in. would that be okay?

**Comment by sdmg15** [comment]
I  don't get you well, the task of checking dupes is already done by awesome-bot I think.

**Comment by iArunava** [comment]
My bad, I misunderstood you completely.
So, my reply to this question 

> isn't there a tool that can check that after each commit ?

No, I am not aware of any such tool.

**Comment by sdmg15** [comment]
:sweat_smile: 
Ok now we agree.

**Comment by iArunava** [comment]
Resolved conflicts, and if there are any issues with the PR then let me know

**Pull request merged**
