### PR TITLE
Added regex101.com to README

### PR DESCRIPTION
**Pull request by alallier**
Not sure I placed it in the proper section but I saw no other good section in the README, might be nice to have a general tools section, or something like that?

### CODE REVIEW

**Comment by ityler** [comment]
I agree a proper "General Tools" section would be a better fit once more is added to fit that category.

**Comment by alallier** [comment]
So is this MR blocking until then or do you want me to add a general tools section?

**Comment by ityler** [comment]
If I had the permission to merge it I would :) @sdmg15

**Comment by sdmg15** [comment]
Note, before @alallier needs to resolve conflicts.

**Comment by alallier** [comment]
@sdmg15 resolved conflicts

**Comment by sdmg15** [comment]
The section is not very appropriate. As @ityler  suggested he can create a section for that and i'll merge.thx

**Comment by alallier** [comment]
I happy to create a section for it or move it to another section at any time. Just let me know hard details on what you want. If @ityler is going to create the section that is fine too, just keep me updated.

**Comment by ityler** [comment]
Thanks for updating it! Added PR for "General Tools" category #92

**Comment by alallier** [comment]
I can send a PR into your branch or I can wait until #92 is merged and update here.

**Comment by alallier** [comment]
Closing never got the chance to make my contribution @sdmg15 just added my link on their own

https://github.com/sdmg15/Best-websites-a-programmer-should-visit/commit/6d3fbb5e50913805c42320d5ab682d7c5a07b6f4

**Pull request closed without merging**
