### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rozhnev**
Add link to SQLtest.online - Free online platform for practicing SQL skills

## Summary of your changes
New link added to collection.

### Checklist

- [v ] My change follows the [Contributing Guidelines](./CONTRIBUTING.md)
- [ v] I have added only one new link to the list.
- [v ] I have checked that the link that I added does NOT exist in the project already.
- [v ] I have sorted the link alphabetically under the related section.

### CODE REVIEW

**Comment by sdmg15** [comment]
Hello, thanks. Typo in the URL.

**Comment by rozhnev** [comment]
Sorry. Fixed now.

**Comment by kyleeliff000-ai** [comment]
I'm very new and just wish I was on your guys's level to be able to run GitHub and use the right applications that good developers had already coded and built. I want to get to the point where I could Bill them but it's going to take years considering I'm going through an apprenticeship for a trade right now but man I wish I I'd had you guysed knowlage

**Comment by kyleeliff000-ai** [comment]
So I'm sorry if I'm trying to run a program and it's totally looking retarded messing up and I'm being stupid I'm just playing around with it

**Pull request merged**
