### PR TITLE
Added Indeed, SimplyHired, CareerBuilder and Dice in Jobs Section.

### PR DESCRIPTION
**Pull request by lalitmee**
[Indeed](https://www.indeed.com)
[SimplyHired](https://www.simplyhired.com)
[CareerBuilder](https://hiring.careerbuilder.com)
[Dice](https://www.dice.com)

### CODE REVIEW

**Comment by lalitmee** [comment]
This pull request showing error in the links of  [Learn to Code With Me](https://learntocodewith.me) and [Learn To Code With Me Podcast](https://learntocodewith.me/podcast/). It is showing that these are Dupes. 
Please tell me the way to solve it. I have added new resources to the jobs section.

**Comment by lalitmee** [comment]
Hey @sdmg15 I added one more resource, and that is [Glassdoor](https://www.glassdoor.co.in) but now Travic CI is showing some issue in this [link](https://stephenhaunts.com/2013/12/11/dieter-rams-10-principles-of-good-product-design/). Actually, I tried to open this link but it is not opening.

I would request you to have a look at this or help me in resolving this error. Since I want to add more resources, but it gives error every time and I don't like that. It's kind of demotivating me.

**Comment by sdmg15** [comment]
Hello, 
As I explained you just make your PRs, I'll resolve that , or you can do so just by opening Travis 
And reading the error message, it's sometime because of "/" at the end of URLs either because of a http Error code or dupes etc.
So don't be discouraged.
Thanks

**Comment by lalitmee** [comment]
So, tell me how to solve dupes error?

**Comment by sdmg15** [comment]
Yeah those links have really issues.
[L317] represent the line at which you can find the link.
You can chose either removing them.

**Comment by lalitmee** [comment]
@sdmg15 you mean to say that I can remove this link?

**Comment by sdmg15** [comment]
Yes you can remove them , cause she opening it's just a connection timeout

**Pull request closed without merging**
